version: '3.1'

services:
  database:
    image: mongo
    restart: always
    container_name: testing-app-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_DATABASE: ${DB_NAME}
      MONGO_USERNAME: ${DB_USER_USERNAME}
      MONGO_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - ${DB_PORT}:27017
    #volumes:
    #    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8111:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: testing-app-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_ROOT_PASSWORD}
